-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-04-29 12:12:07 MYT
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

set echo on 
SPOOL oo_schema_output.txt

--student id: 33590966
--student name: OOI HUI XIA

DROP TABLE ADDRESS CASCADE CONSTRAINTS 
;

DROP TABLE CABIN CASCADE CONSTRAINTS 
;

DROP TABLE COUNTRY CASCADE CONSTRAINTS 
;

DROP TABLE CRUISE CASCADE CONSTRAINTS 
;

DROP TABLE ITINERARY CASCADE CONSTRAINTS 
;

DROP TABLE MANIFEST_INSTANCE CASCADE CONSTRAINTS 
;

DROP TABLE OPERATOR CASCADE CONSTRAINTS 
;

DROP TABLE PASSENGER CASCADE CONSTRAINTS 
;

DROP TABLE PORT CASCADE CONSTRAINTS 
;

DROP TABLE SHIP CASCADE CONSTRAINTS 
;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE ADDRESS 
    ( 
     address_id       NUMBER (7)  NOT NULL , 
     address_street   VARCHAR2 (50)  NOT NULL , 
     address_town     VARCHAR2 (50)  NOT NULL , 
     address_postcode NUMBER (7)  NOT NULL , 
     country_code     VARCHAR2 (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN ADDRESS.address_id IS 'address id (Suggorate key)' 
;

COMMENT ON COLUMN ADDRESS.address_street IS 'address street' 
;

COMMENT ON COLUMN ADDRESS.address_town IS 'address town' 
;

COMMENT ON COLUMN ADDRESS.address_postcode IS 'address postcode' 
;

COMMENT ON COLUMN ADDRESS.country_code IS 'Country code' 
;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_PK PRIMARY KEY ( address_id ) ;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT ADDRESS_NK UNIQUE ( address_street , address_town , address_postcode , country_code ) ;

CREATE TABLE CABIN 
    ( 
     cabin_no        NUMBER (7)  NOT NULL , 
     ship_code       NUMBER (7)  NOT NULL , 
     cabin_class     CHAR (1)  NOT NULL , 
     cabin_sleep_cap NUMBER (10)  NOT NULL 
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT chk_cabin_class 
    CHECK (cabin_class IN ('B', 'I', 'O', 'S')) 
;

COMMENT ON COLUMN CABIN.cabin_no IS 'cabin number (PK)' 
;

COMMENT ON COLUMN CABIN.ship_code IS 'ship code (PK)' 
;

COMMENT ON COLUMN CABIN.cabin_class IS 'Cabin class (B-Balcony, I-Interior, O-Ocean view, S-Suite)' 
;

COMMENT ON COLUMN CABIN.cabin_sleep_cap IS 'cabin sleeping capacity' 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT CABIN_PK PRIMARY KEY ( cabin_no, ship_code ) ;

CREATE TABLE COUNTRY 
    ( 
     country_code VARCHAR2 (7)  NOT NULL , 
     country_name VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN COUNTRY.country_code IS 'Country code' 
;

COMMENT ON COLUMN COUNTRY.country_name IS 'country name' 
;

ALTER TABLE COUNTRY 
    ADD CONSTRAINT COUNTRY_PK PRIMARY KEY ( country_code ) ;

CREATE TABLE CRUISE 
    ( 
     cruise_id              NUMBER (7)  NOT NULL , 
     cruise_name            VARCHAR2 (50)  NOT NULL , 
     cruise_desc            VARCHAR2 (50)  NOT NULL , 
     cruise_depart_datetime DATE  NOT NULL , 
     cost_per_person        NUMBER (7)  NOT NULL , 
     ship_code              NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN CRUISE.cruise_id IS 'cruise ID (PK)' 
;

COMMENT ON COLUMN CRUISE.cruise_name IS 'Name of the cruise' 
;

COMMENT ON COLUMN CRUISE.cruise_desc IS 'Description of the cruise' 
;

COMMENT ON COLUMN CRUISE.cruise_depart_datetime IS 'The date and time where cruise depart' 
;

COMMENT ON COLUMN CRUISE.cost_per_person IS 'Cost per person' 
;

COMMENT ON COLUMN CRUISE.ship_code IS 'ship code (PK)' 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT CRUISE_PK PRIMARY KEY ( cruise_id ) ;

CREATE TABLE ITINERARY 
    ( 
     itinerary_id        NUMBER (7)  NOT NULL , 
     cruise_id           NUMBER (7)  NOT NULL , 
     port_code           VARCHAR2 (7)  NOT NULL , 
     itinerary_date_time DATE  NOT NULL , 
     departure_arrival   CHAR (1)  NOT NULL 
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT chk_departurearrival 
    CHECK (departure_arrival IN ('A', 'D')) 
;

COMMENT ON COLUMN ITINERARY.itinerary_id IS 'itinerary id (Suggorate key). 
' 
;

COMMENT ON COLUMN ITINERARY.cruise_id IS 'cruise ID (PK)' 
;

COMMENT ON COLUMN ITINERARY.port_code IS 'port code' 
;

COMMENT ON COLUMN ITINERARY.itinerary_date_time IS 'Itinerary depart or arrive date and time' 
;

COMMENT ON COLUMN ITINERARY.departure_arrival IS 'Departure or arrival (D-Depart, A-Arrive)' 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT ITINERARY_PK PRIMARY KEY ( itinerary_id ) ;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT ITINERARY_NK UNIQUE ( cruise_id , port_code , itinerary_date_time ) ;

CREATE TABLE MANIFEST_INSTANCE 
    ( 
     cruise_id           NUMBER (7)  NOT NULL , 
     passenger_id        NUMBER (7)  NOT NULL , 
     man_fboard_datetime DATE , 
     cabin_no            NUMBER (7)  NOT NULL , 
     ship_code           NUMBER (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN MANIFEST_INSTANCE.cruise_id IS 'cruise ID (PK)' 
;

COMMENT ON COLUMN MANIFEST_INSTANCE.passenger_id IS 'passenger id (PK)' 
;

COMMENT ON COLUMN MANIFEST_INSTANCE.man_fboard_datetime IS 'The date and time when passenger first boarded the ship' 
;

COMMENT ON COLUMN MANIFEST_INSTANCE.cabin_no IS 'cabin number (PK)' 
;

COMMENT ON COLUMN MANIFEST_INSTANCE.ship_code IS 'ship code (PK)' 
;

ALTER TABLE MANIFEST_INSTANCE 
    ADD CONSTRAINT MANIFEST_INSTANCE_PK PRIMARY KEY ( cruise_id, passenger_id ) ;

CREATE TABLE OPERATOR 
    ( 
     operator_id           NUMBER (7)  NOT NULL , 
     operator_company_name VARCHAR2 (50)  NOT NULL , 
     operator_ceo_name     VARCHAR2 (50)  NOT NULL 
    ) 
;

COMMENT ON COLUMN OPERATOR.operator_id IS 'operator ID (PK)' 
;

COMMENT ON COLUMN OPERATOR.operator_company_name IS 'the company''s name' 
;

COMMENT ON COLUMN OPERATOR.operator_ceo_name IS 'Chief Executive Officer''s name' 
;

ALTER TABLE OPERATOR 
    ADD CONSTRAINT OPERATOR_PK PRIMARY KEY ( operator_id ) ;

CREATE TABLE PASSENGER 
    ( 
     passenger_id     NUMBER (7)  NOT NULL , 
     passenger_fname  VARCHAR2 (50) , 
     passenger_lname  VARCHAR2 (50) , 
     passenger_gender CHAR (1)  NOT NULL , 
     passenger_dob    DATE  NOT NULL , 
     passenger_phone  CHAR (10) , 
     address_id       NUMBER (7)  NOT NULL , 
     guardian_id      NUMBER (7) 
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT chk_passengergender 
    CHECK (passenger_gender IN ('F', 'M')) 
;

COMMENT ON COLUMN PASSENGER.passenger_id IS 'passenger id (PK)' 
;

COMMENT ON COLUMN PASSENGER.passenger_fname IS 'passenger first name' 
;

COMMENT ON COLUMN PASSENGER.passenger_lname IS 'passenger last name' 
;

COMMENT ON COLUMN PASSENGER.passenger_gender IS 'passenger gender (F - Female, M - Male)' 
;

COMMENT ON COLUMN PASSENGER.passenger_dob IS 'passenger date of birth' 
;

COMMENT ON COLUMN PASSENGER.passenger_phone IS 'passenger contact phone number' 
;

COMMENT ON COLUMN PASSENGER.address_id IS 'address id (Suggorate key)' 
;

COMMENT ON COLUMN PASSENGER.guardian_id IS 'passenger id (PK)' 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT PASSENGER_PK PRIMARY KEY ( passenger_id ) ;

CREATE TABLE PORT 
    ( 
     port_code      VARCHAR2 (7)  NOT NULL , 
     port_name      VARCHAR2 (50)  NOT NULL , 
     port_latitude  NUMBER (10)  NOT NULL , 
     port_longitude NUMBER (10)  NOT NULL , 
     country_code   VARCHAR2 (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN PORT.port_code IS 'port code' 
;

COMMENT ON COLUMN PORT.port_name IS 'port name' 
;

COMMENT ON COLUMN PORT.port_latitude IS 'port latitude' 
;

COMMENT ON COLUMN PORT.port_longitude IS 'port longitude' 
;

COMMENT ON COLUMN PORT.country_code IS 'Country code' 
;

ALTER TABLE PORT 
    ADD CONSTRAINT PORT_PK PRIMARY KEY ( port_code ) ;

CREATE TABLE SHIP 
    ( 
     ship_code               NUMBER (7)  NOT NULL , 
     ship_name               VARCHAR2 (50)  NOT NULL , 
     ship_commision_date     DATE  NOT NULL , 
     ship_tonnage            NUMBER (10)  NOT NULL , 
     ship_max_guest_capacity NUMBER (10)  NOT NULL , 
     operator_id             NUMBER (7)  NOT NULL , 
     country_code            VARCHAR2 (7)  NOT NULL 
    ) 
;

COMMENT ON COLUMN SHIP.ship_code IS 'ship code (PK)' 
;

COMMENT ON COLUMN SHIP.ship_name IS 'ship''s name' 
;

COMMENT ON COLUMN SHIP.ship_commision_date IS 'ship commision date' 
;

COMMENT ON COLUMN SHIP.ship_tonnage IS 'ship''s tonnage' 
;

COMMENT ON COLUMN SHIP.ship_max_guest_capacity IS 'ship maximum guest capacity' 
;

COMMENT ON COLUMN SHIP.operator_id IS 'operator ID (PK)' 
;

COMMENT ON COLUMN SHIP.country_code IS 'Country code' 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT SHIP_PK PRIMARY KEY ( ship_code ) ;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT address_passenger_fk FOREIGN KEY 
    ( 
     address_id
    ) 
    REFERENCES ADDRESS 
    ( 
     address_id
    ) 
;

ALTER TABLE MANIFEST_INSTANCE 
    ADD CONSTRAINT cabin_manifestinstance_fk FOREIGN KEY 
    ( 
     cabin_no,
     ship_code
    ) 
    REFERENCES CABIN 
    ( 
     cabin_no,
     ship_code
    ) 
;

ALTER TABLE ADDRESS 
    ADD CONSTRAINT country_address_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE PORT 
    ADD CONSTRAINT country_port_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT country_ship_fk FOREIGN KEY 
    ( 
     country_code
    ) 
    REFERENCES COUNTRY 
    ( 
     country_code
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT cruise_itinerary_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE MANIFEST_INSTANCE 
    ADD CONSTRAINT cruise_manifestinstance_fk FOREIGN KEY 
    ( 
     cruise_id
    ) 
    REFERENCES CRUISE 
    ( 
     cruise_id
    ) 
;

ALTER TABLE PASSENGER 
    ADD CONSTRAINT guardian_minor_fk FOREIGN KEY 
    ( 
     guardian_id
    ) 
    REFERENCES PASSENGER 
    ( 
     passenger_id
    ) 
;

ALTER TABLE SHIP 
    ADD CONSTRAINT operator_ship_fk FOREIGN KEY 
    ( 
     operator_id
    ) 
    REFERENCES OPERATOR 
    ( 
     operator_id
    ) 
;

ALTER TABLE MANIFEST_INSTANCE 
    ADD CONSTRAINT passenger_manifestinstance_fk FOREIGN KEY 
    ( 
     passenger_id
    ) 
    REFERENCES PASSENGER 
    ( 
     passenger_id
    ) 
;

ALTER TABLE ITINERARY 
    ADD CONSTRAINT port_itinerary FOREIGN KEY 
    ( 
     port_code
    ) 
    REFERENCES PORT 
    ( 
     port_code
    ) 
;

ALTER TABLE CABIN 
    ADD CONSTRAINT ship_cabin_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;

ALTER TABLE CRUISE 
    ADD CONSTRAINT ship_cruise_fk FOREIGN KEY 
    ( 
     ship_code
    ) 
    REFERENCES SHIP 
    ( 
     ship_code
    ) 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             28
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


SPOOL off
set echo off